server {
  listen 80;

  location /api/auth/ {
    proxy_pass http://auth-service:3001/;
  }

  location /api/store/ {
    proxy_pass http://store-service:3002/;
  }

  location /api/users/ {
    proxy_pass http://user-service:3003/;
  }
}
